# Generated by Django 3.1.4 on 2020-12-12 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(db_index=True, max_length=32, verbose_name='vin')),
                ('color', models.CharField(max_length=32, verbose_name='color')),
                ('brand', models.CharField(max_length=32, verbose_name='brand')),
                ('Car_Type', models.IntegerField(choices=[(1, 'dj'), (2, 'django'), (3, 'rest'), (4, 'framework')], verbose_name='Car_Type')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
